// Kim Thành Đông — business dataset.
// Mirrors the Claude Design prototype (ktd-data.js) and spec D2 field structure.
// Replace with the real Excel import when the operations team finishes it.

import { slugify } from './utils'

export interface Brand {
  slug: string
  name: string
  origin: string
  desc: string
  /** Path under /public. Undefined = show the neutral "LOGO" placeholder. */
  logo?: string
}

export interface Category {
  slug: string
  name: string
  /** Dòng chữ nhỏ liệt kê nhóm thiết bị — thay cho số đếm sản phẩm. */
  sub: string
}

export interface Product {
  part: string
  name: string
  brand: string
  category: string
  sub?: string
  series: string
  origin: string
  featured?: boolean
  tag?: 'Mới' | 'Bán chạy'
  /** Câu giới thiệu ngắn, dùng cho card và phần đầu trang chi tiết. */
  desc: string
  /** Mô tả đầy đủ theo từng đoạn, dùng cho tab "Mô tả". */
  descFull?: string[]
  /** Ứng dụng thực tế do hãng cung cấp; thiếu thì suy ra từ danh mục. */
  applications?: string[]
  /** Ảnh sản phẩm thật, tối đa 5 (spec C3). Thiếu thì hiện ô placeholder. */
  images?: string[]
  specs?: [string, string][]
  kw: string[]
  /** Catalog series — dữ liệu demo. */
  pdf?: { name: string; size: string; pages: number }
  /** Datasheet PDF thật kèm theo sản phẩm. */
  docPdf?: string
  /** Trang sản phẩm trên website hãng. */
  docUrl?: string
}

export interface Article {
  slug: string
  cat: string
  date: string
  title: string
  excerpt: string
}

export const BRANDS: Brand[] = [
  // Thứ tự ở đây là thứ tự ưu tiên hiển thị (dải logo trang chủ và cách gom
  // nhóm ở trang sản phẩm). 8 hãng đầu theo chỉ định trong tài liệu SỬA WEB;
  // phần còn lại giữ nguyên, chờ danh sách đầy đủ.
  { slug: 'martor', name: 'Martor', origin: 'Đức', desc: 'Thương hiệu hàng đầu về giải pháp cắt an toàn: dao an toàn, kéo an toàn, lưỡi dao và dụng cụ cắt chuyên dụng cho môi trường công nghiệp.', logo: '/assets/brands/norm/martor.webp' },
  { slug: 'morrisflex', name: 'Morrisflex', origin: 'Ireland', desc: 'Thương hiệu thuộc ATA Group, chuyên mũi mài carbide và dụng cụ mài phục vụ gia công, sửa nguội và hoàn thiện kim loại.', logo: '/assets/brands/norm/morrisflex.webp' },
  { slug: 'ata', name: 'ATA Air Tools', origin: 'Ireland', desc: 'Thương hiệu dụng cụ khí nén công nghiệp của ATA Group, chuyên máy mài, máy chà nhám và thiết bị hoàn thiện bề mặt.', logo: '/assets/brands/norm/ata.webp' },
  { slug: 'technomark', name: 'Technomark', origin: 'Pháp', desc: 'Chuyên gia về đánh dấu và truy xuất công nghiệp, với các hệ thống khắc chấm và khắc laser được thiết kế, sản xuất tại Pháp.' },
  { slug: 'lenzkes', name: 'Lenzkes', origin: 'Đức', desc: 'Nhà cung cấp hàng đầu hệ thống kẹp nhanh cho khuôn và phôi, giúp rút ngắn thời gian thay đổi và nâng cao hiệu quả vận hành máy.', logo: '/assets/brands/norm/lenzkes.webp' },
  { slug: 'tschorn', name: 'TSChorn', origin: 'Đức', desc: 'Thương hiệu dụng cụ đo và căn chỉnh chính xác cho gia công CNC, nổi bật với đầu dò 3D, dò cạnh và thiết bị xác định vị trí gia công.', logo: '/assets/brands/norm/tschorn.webp' },
  { slug: 'fiam', name: 'Fiam', origin: 'Ý', desc: 'Chuyên gia về công nghệ siết công nghiệp, cung cấp dụng cụ và hệ thống siết kiểm soát lực cho các dây chuyền lắp ráp.', logo: '/assets/brands/norm/fiam.webp' },
  { slug: 'tecna', name: 'Tecna', origin: 'Ý', desc: 'Nhà sản xuất thiết bị hàn điện trở, thiết bị kiểm tra thông số hàn và hệ thống pa lăng cân bằng tải phục vụ sản xuất công nghiệp.', logo: '/assets/brands/norm/tecna.webp' },
  { slug: 'helical', name: 'HELICAL SOLUTIONS', origin: 'Mỹ', desc: 'Thương hiệu dụng cụ phay carbide hiệu suất cao, cung cấp các giải pháp dao phay chuyên dụng cho nhiều vật liệu và ứng dụng gia công CNC.' },
  { slug: 'corehog', name: 'Corehog', origin: 'Mỹ', desc: 'Thương hiệu dụng cụ cắt chuyên biệt cho composite, với dao phay, mũi khoan và dụng cụ gia công CFRP, fiberglass và cấu trúc honeycomb.', logo: '/assets/brands/norm/corehog.webp' },
  { slug: 'bevel-tools', name: 'Bevel Tools', origin: 'Hà Lan', desc: 'Chuyên gia về vát mép và bo cạnh kim loại, cung cấp máy cùng dao cắt chuyên dụng cho chuẩn bị mép hàn và hoàn thiện cạnh.' },
  { slug: 'rocklinizer', name: 'ROCKLIN', origin: 'Mỹ', desc: 'Nhà sản xuất các công nghệ phục hồi và tăng tuổi thọ bề mặt kim loại, nổi bật với Rocklinizer® và hệ thống sửa khuôn MoldMender®.', logo: '/assets/brands/norm/rocklinizer.webp' },
  { slug: 'buchem', name: 'Buchem', origin: 'Đức', desc: 'Chuyên cung cấp các sản phẩm vệ sinh cho ngành khuôn mẫu và ép nhựa.', logo: '/assets/brands/norm/buchem.webp' },
  { slug: 'diprofil', name: 'Diprofil', origin: 'Thụy Điển', desc: 'Thương hiệu chuyên dụng cụ và thiết bị đánh bóng, giũa và hoàn thiện chính xác, đặc biệt cho ngành khuôn mẫu và gia công tinh.', logo: '/assets/brands/norm/diprofil.webp' },
  { slug: 'rtc', name: 'RTC', origin: 'Đức', desc: 'Chuyên công nghệ khớp nối nhanh cho khí nén, thủy lực, nước và các môi chất công nghiệp, với danh mục hơn 10.000 sản phẩm và phụ kiện.', logo: '/assets/brands/norm/rtc.webp' },
  { slug: 'sloky', name: 'Sloky', origin: 'Đài Loan', desc: 'Chuyên dụng cụ siết lực cầm tay với hệ thống tô vít lực và đầu nối kiểm soát mô-men, giúp hạn chế siết quá lực và bảo vệ dụng cụ.', logo: '/assets/brands/norm/sloky.webp' },
  { slug: 'hartner', name: 'Hartner', origin: 'Đức', desc: 'Thương hiệu dụng cụ cắt gọt chuyên sâu với các giải pháp khoan, ta rô, doa và gia công lỗ cho sản xuất cơ khí.', logo: '/assets/brands/norm/hartner.webp' },
  { slug: 'karnasch', name: 'Karnasch', origin: 'Đức', desc: 'Thương hiệu dụng cụ gia công hiệu suất cao với danh mục chuyên sâu về khoan, phay, khoét, ta rô và các dụng cụ cắt gọt kim loại.', logo: '/assets/brands/norm/karnasch.webp' },
]

export const CATEGORIES: Category[] = [
  { slug: 'an-toan', name: 'Dụng cụ an toàn', sub: 'Dao, kéo an toàn, lưỡi dao & phụ kiện' },
  { slug: 'cat-got-cnc', name: 'Dụng cụ cắt gọt CNC', sub: 'Mũi khoan, dao phay, mũi khoét, ta rô' },
  { slug: 'mai-hoan-thien', name: 'Mài, đánh bóng & hoàn thiện bề mặt', sub: 'Máy mài, mũi mài, dụng cụ đánh bóng' },
  { slug: 'kep-khuon-phoi', name: 'Kẹp khuôn & Kẹp phôi', sub: 'Kẹp khuôn, kẹp phôi, phụ kiện gá kẹp' },
  { slug: 'do-can-chinh', name: 'Thiết bị đo & Căn chỉnh gia công', sub: 'Đầu dò 3D, Dò cạnh, Xác định điểm 0' },
  { slug: 'danh-dau', name: 'Đánh dấu & truy xuất', sub: 'Khắc chấm, Khắc laser, Truy xuất nguồn gốc' },
  { slug: 'nang-ha', name: 'Thiết bị nâng hạ & công thái học', sub: 'Pa lăng cân bằng, Bộ cân bằng tải, Phụ kiện' },
  { slug: 'siet-cong-nghiep', name: 'Thiết bị siết công nghiệp', sub: 'Tô vít công nghiệp, Máy siết bu lông, Hệ thống siết lực tự động' },
  { slug: 'siet-luc-cam-tay', name: 'Dụng cụ siết lực cầm tay', sub: 'Tô vít lực, Đầu vít, Phụ kiện' },
  { slug: 'vat-mep', name: 'Máy vát mép & bo cạnh', sub: 'Vát mép, Bo tròn cạnh, Chuẩn bị mép hàn' },
  { slug: 'composite', name: 'Dụng cụ gia công composite', sub: 'Dao phay, Mũi khoan, Dụng cụ Honeycomb' },
  { slug: 'do-kiem-may-han', name: 'Thiết bị đo & Kiểm tra máy hàn', sub: 'Đo dòng điện hàn và lực ép' },
  { slug: 'phuc-hoi-be-mat', name: 'Xử lý & phục hồi bề mặt kim loại', sub: 'Phủ carbide, Sửa chữa khuôn, Phục hồi bề mặt' },
  { slug: 'khop-noi', name: 'Khớp nối nhanh công nghiệp', sub: 'Khớp nối khí, thủy lực & Khớp nối khác' },
  { slug: 've-sinh-khuon', name: 'Vệ sinh & Bảo trì khuôn', sub: 'Vệ sinh khuôn và trục vít' },
]


/** Spec C4 ★ — shop-floor slang mapped onto standard technical terms. */
export const SLANG_MAP: Record<string, string> = {
  'mui mai ca rem': 'morrisflex mũi mài hợp kim',
  'dao roc giay an toan': 'martor dao an toàn',
  'ba lang': 'tecna pa lăng cân bằng',
  'pa lang': 'tecna pa lăng cân bằng',
  palang: 'tecna pa lăng cân bằng',
  'may khac chu len sat': 'technomark máy khắc dấu',
  'sung mai hoi': 'ata máy mài khí nén',
  'cao thuy luc': 'vật tư thủy lực',
  'to vit luc': 'sloky tua vít lực',
  'tua vit luc': 'sloky tua vít lực',
}

/** Ngành ứng dụng theo từng danh mục — dùng cho tab "Ứng dụng" ở trang chi
    tiết sản phẩm. Tên ngành khớp với SECTOR_CARDS trong lib/constants.ts. */
export const CATEGORY_SECTORS: Record<string, string[]> = {
  'an-toan': ['Ô tô & linh kiện', 'Điện tử & lắp ráp chính xác', 'Khuôn mẫu & ép nhựa'],
  'cat-got-cnc': ['Gia công cơ khí & CNC', 'Hàng không vũ trụ', 'Đóng tàu & kết cấu kim loại'],
  'mai-hoan-thien': ['Gia công cơ khí & CNC', 'Đóng tàu & kết cấu kim loại', 'Khuôn mẫu & ép nhựa'],
  'kep-khuon-phoi': ['Khuôn mẫu & ép nhựa', 'Gia công cơ khí & CNC'],
  've-sinh-khuon': ['Khuôn mẫu & ép nhựa'],
  'do-can-chinh': ['Gia công cơ khí & CNC', 'Khuôn mẫu & ép nhựa'],
  'danh-dau': ['Ô tô & linh kiện', 'Dầu khí & năng lượng', 'Điện tử & lắp ráp chính xác'],
  'nang-ha': ['Ô tô & linh kiện', 'Đóng tàu & kết cấu kim loại', 'Điện tử & lắp ráp chính xác'],
  'siet-cong-nghiep': ['Ô tô & linh kiện', 'Điện tử & lắp ráp chính xác'],
  'siet-luc-cam-tay': ['Điện tử & lắp ráp chính xác', 'Gia công cơ khí & CNC'],
  'vat-mep': ['Đóng tàu & kết cấu kim loại', 'Gia công cơ khí & CNC'],
  'composite': ['Hàng không vũ trụ', 'Gia công cơ khí & CNC'],
  'do-kiem-may-han': ['Ô tô & linh kiện', 'Đóng tàu & kết cấu kim loại'],
  'phuc-hoi-be-mat': ['Khuôn mẫu & ép nhựa', 'Gia công cơ khí & CNC'],
  'khop-noi': ['Gia công cơ khí & CNC', 'Dầu khí & năng lượng'],
}

export const PRODUCTS: Product[] = [
  // --- Martor: dữ liệu và ảnh thật do hãng cung cấp ---
  {
    part: '1031.50', name: 'Lưỡi dao SCALPEL 1031', brand: 'martor', category: 'an-toan',
    series: '1031', origin: 'Đức',
    desc: 'Lưỡi dao MARTOR SCALPEL 1031 No.1031.50 là lưỡi dao thay thế chính hãng của MARTOR, được thiết kế chuyên dụng cho các công việc cắt chính xác cao trong kỹ thuật và sản xuất công nghiệp.',
    descFull: [
      'Lưỡi dao MARTOR SCALPEL 1031 No.1031.50 là lưỡi dao thay thế chính hãng của MARTOR, được thiết kế chuyên dụng cho các công việc cắt chính xác cao trong kỹ thuật và sản xuất công nghiệp.',
      'Lưỡi dao có độ sắc bén cao và độ ổn định tốt, giúp tạo đường cắt mịn, chính xác và kiểm soát tốt trong các thao tác kỹ thuật tinh xảo. Sản phẩm phù hợp cho các môi trường làm việc yêu cầu độ chính xác cao như điện – điện tử, phòng kỹ thuật, cơ khí chính xác và phòng sạch.',
      'Lắp đặt cho:GRAFIX CLAPPEX KLEIN, TRIMMEX CUTTOGRAF',
      'Ưu điểm nổi bật',
      'Độ sắc bén cao – cắt chính xác',
      'Thiết kế lưỡi mảnh giúp thao tác cắt chi tiết và chính xác trên các vật liệu nhỏ hoặc mỏng.',
      'Chất liệu thép chất lượng cao',
      'Lưỡi dao được chế tạo từ thép cao cấp giúp giữ độ sắc lâu và tăng độ bền khi sử dụng.',
      'Độ ổn định và đồng đều cao',
      'Sản xuất theo tiêu chuẩn chất lượng của MARTOR, đảm bảo hiệu suất cắt ổn định.',
      'Thay lưỡi nhanh chóng và an toàn',
      'Thiết kế chuẩn giúp lắp đặt và thay thế lưỡi dao dễ dàng.',
      'Ứng dụng',
      'Cắt chi tiết kỹ thuật',
      'Cắt vật liệu mỏng và linh kiện nhỏ',
      'Công việc điện – điện tử',
      'Gia công cơ khí chính xác',
      'Phòng sạch và phòng kỹ thuật',
      'Thông số kỹ thuật',
      'Model: SCALPEL 1031 No.1031.50',
      'Quy cách đóng gói: 10 lưỡi / hộp',
      'Chất liệu: Thép chất lượng cao',
      'Dòng lưỡi: SCALPEL 1031',
      'Xuất xứ: Đức (Germany)',
      'Phù hợp cho người dùng cần lưỡi dao scalpel Martor chính hãng, lưỡi dao cắt chính xác cho kỹ thuật, điện tử và gia công chi tiết.',
      '-----------------------',
      'The MARTOR SCALPEL Blade 1031 No.1031.50 is an original precision replacement blade designed for technical scalpel knives from MARTOR (Germany).',
      'This blade is engineered for high-precision cutting tasks in industrial production, electronics, laboratories, and technical workshops.',
      'Made from high-quality steel, the blade ensures consistent sharpness, clean cuts, and reliable performance in delicate cutting operations.',
      'Mountable in:',
      'GRAFIX CLAPPEX KLEIN, TRIMMEX CUTTOGRAF',
      'Key Features',
      'High-precision scalpel blade',
      'High-quality steel construction',
      'Consistent sharpness and durability',
      'Ideal for technical and industrial applications',
      'Applications',
      'Precision cutting tasks',
      'Electronics and electrical work',
      'Cleanroom environments',
      'Precision engineering and manufacturing',
      'Specifications',
      'Model: SCALPEL 1031 No.1031.50',
      'Pack size: 10 blades per box',
      'Material: High-quality steel',
      'Blade series: SCALPEL 1031',
      'Origin: Germany',
      '#daoantoanmartor #daoantoan #daocatantoan #martorchinhhang #daocongnghiep #daorocthung #daorocmangphim #daocatdai #luoidaomartor',
    ],
    applications: [
      'Cắt chi tiết kỹ thuật',
      'Cắt vật liệu mỏng và linh kiện nhỏ',
      'Công việc điện – điện tử',
      'Gia công cơ khí chính xác',
      'Phòng sạch và phòng kỹ thuật',
    ],
    images: [
      '/products/martor/luoi-dao-scalpel-1031-1031-50-1.webp',
      '/products/martor/luoi-dao-scalpel-1031-1031-50-2.webp',
      '/products/martor/luoi-dao-scalpel-1031-1031-50-3.webp',
    ],
    kw: ['dao an toan', 'martor', 'luoi dao scalpel 1031'],
  },
  {
    part: '12.50', name: 'Lưỡi dao SCALPEL 12', brand: 'martor', category: 'an-toan',
    series: '12', origin: 'Đức',
    desc: 'Lưỡi dao MARTOR SCALPEL 12 No.12.50 là lưỡi dao thay thế chính hãng của MARTOR, được thiết kế chuyên dụng cho các công việc cắt chính xác và thao tác tinh xảo trong môi trường kỹ thuật và công nghiệp.',
    descFull: [
      'Lưỡi dao MARTOR SCALPEL 12 No.12.50 là lưỡi dao thay thế chính hãng của MARTOR, được thiết kế chuyên dụng cho các công việc cắt chính xác và thao tác tinh xảo trong môi trường kỹ thuật và công nghiệp.',
      'Lưỡi dao được chế tạo từ thép chất lượng cao, đảm bảo độ sắc bén và độ ổn định khi thao tác cắt các vật liệu mỏng hoặc chi tiết nhỏ. Thiết kế lưỡi mảnh và sắc giúp người dùng kiểm soát đường cắt tốt hơn, phù hợp cho các công việc yêu cầu độ chính xác cao.',
      'Sản phẩm thường được sử dụng trong ngành điện tử, cơ khí chính xác, phòng thí nghiệm, phòng sạch, ngành đồ họa và kỹ thuật.',
      'Thay thế cho các dòng dao:',
      'GRAFIX SCALPELL SMALL, TRIMMEX CUTTOGRAF.',
      'Ưu điểm nổi bật',
      'Lưỡi dao MARTOR chính hãng – Đức',
      'Đảm bảo chất lượng và độ sắc bén tiêu chuẩn công nghiệp.',
      'Thiết kế lưỡi cắt chính xác',
      'Phù hợp cho các thao tác cắt chi tiết và công việc tinh xảo.',
      'Thép chất lượng cao',
      'Mang lại hiệu suất cắt ổn định và độ bền cao.',
      'Đóng gói tiện lợi',
      'Hộp 10 lưỡi dao, phù hợp cho sử dụng trong môi trường kỹ thuật và sản xuất.',
      'Thông số kỹ thuật',
      'Model: No.12.50',
      'Dòng lưỡi: SCALPEL 12',
      'Quy cách đóng gói: 10 lưỡi / hộp',
      'Chất liệu: Thép chất lượng cao',
      'Ứng dụng: Cắt chính xác, thao tác kỹ thuật tinh',
      'Xuất xứ: Đức',
      'Ứng dụng',
      'Cắt chi tiết trong điện tử',
      'Gia công cơ khí chính xác',
      'Sử dụng trong phòng thí nghiệm và phòng sạch',
      'Cắt giấy, decal, vật liệu mỏng',
      'Công việc kỹ thuật và đồ họa',
      '-------------',
      'The MARTOR SCALPEL Blade No.12.50 is an original precision replacement blade manufactured by MARTOR in Germany. It is specifically designed for fine cutting tasks requiring high precision and control.',
      'Made from high-quality steel, the blade provides excellent sharpness and stability, ensuring clean and accurate cuts on delicate materials. Its slim design allows users to achieve precise cutting results in technical and professional applications.',
      'This blade is commonly used in electronics, precision engineering, laboratories, cleanrooms, and technical or graphic applications.',
      'Mountable in: GRAFIX SCALPELL SMALL, TRIMMEX CUTTOGRAF.',
      'Key Features',
      'Original MARTOR blade – Made in Germany',
      'High precision scalpel blade design',
      'High-quality steel for durability and sharpness',
      'Ideal for fine cutting and technical applications',
      'Pack of 10 blades for professional use',
      '#daoantoanmartor #daoantoan #daocatantoan #martorchinhhang #daocongnghiep #daorocthung #daorocmangphim #daocatdai #luoidaomartor',
    ],
    applications: [
      'Cắt chi tiết trong điện tử',
      'Gia công cơ khí chính xác',
      'Sử dụng trong phòng thí nghiệm và phòng sạch',
      'Cắt giấy, decal, vật liệu mỏng',
      'Công việc kỹ thuật và đồ họa',
    ],
    images: [
      '/products/martor/luoi-dao-scalpel-12-12-50-1.webp',
    ],
    docPdf: '/catalogs/martor/luoi-dao-scalpel-12-12-50.pdf',
    kw: ['dao an toan', 'martor', 'luoi dao scalpel 12'],
  },
  {
    part: '145001.12', name: 'SECUMAX 145', brand: 'martor', category: 'an-toan',
    series: 'SECUMAX', origin: 'Đức',
    desc: 'Dao an toàn MARTOR SECUMAX 145 No.145001.12 là dòng dao cắt an toàn lưỡi ẩn của MARTOR, được thiết kế chuyên dụng cho các công việc cắt bao bì và vật liệu đóng gói trong kho vận, logistics và dây chuyền sản xuất.',
    descFull: [
      'Dao an toàn MARTOR SECUMAX 145 No.145001.12 là dòng dao cắt an toàn lưỡi ẩn của MARTOR, được thiết kế chuyên dụng cho các công việc cắt bao bì và vật liệu đóng gói trong kho vận, logistics và dây chuyền sản xuất.',
      'Dao thuộc dòng SECUMAX, nổi bật với lưỡi dao được che chắn hoàn toàn, giúp giảm thiểu tối đa nguy cơ tai nạn lao động và hạn chế làm hư hỏng hàng hóa trong quá trình cắt.',
      'Thiết kế nhỏ gọn, nhẹ và dễ sử dụng giúp người dùng thao tác nhanh và chính xác trên các vật liệu như màng nhựa, bao bì mỏng và dây đai nhựa.',
      'Ưu điểm nổi bật',
      'Lưỡi dao che chắn hoàn toàn – an toàn tối đa',
      'Thiết kế lưỡi ẩn giúp giảm nguy cơ cắt trúng tay và bảo vệ hàng hóa.',
      'Thiết kế nhỏ gọn và nhẹ',
      'Dễ cầm nắm, thao tác linh hoạt trong quá trình làm việc.',
      'Chất liệu nhựa kỹ thuật bền bỉ',
      'Thân dao được làm từ nhựa kỹ thuật cao cấp, có độ bền và khả năng chịu va đập tốt.',
      'Hiệu suất cắt ổn định',
      'Phù hợp cho các công việc cắt bao bì và vật liệu đóng gói thường xuyên.',
      'Thông số kỹ thuật',
      'Model: SECUMAX 145 No.145001.12',
      'Dòng sản phẩm: SECUMAX 145',
      'Quy cách đóng gói: 10 cái / hộp',
      'Chất liệu thân dao: Nhựa kỹ thuật',
      'Cơ chế an toàn: Lưỡi cắt che chắn cố định (Concealed blade)',
      'Xuất xứ: Đức (Germany)',
      'Ứng dụng',
      'Cắt màng nhựa PE, PVC',
      'Cắt bao bì mỏng',
      'Cắt dây đai nhựa',
      'Sử dụng trong kho vận, logistics và dây chuyền đóng gói',
      '---------------',
      'The MARTOR SECUMAX 145 No.145001.12 is a professional concealed blade safety cutter designed for packaging and warehouse operations. Manufactured by MARTOR (Germany), it provides high safety standards for industrial cutting tasks.',
      'The cutter features a fully concealed blade, reducing the risk of injuries while also protecting packaged goods during cutting operations.',
      'Its compact and lightweight design makes it ideal for cutting plastic film, thin packaging materials, and plastic strapping in logistics and manufacturing environments.',
      'Key Features',
      'Fully concealed blade for maximum safety',
      'Compact and lightweight design',
      'Durable technical plastic handle',
      'Reliable cutting performance for packaging materials',
      'Applications',
      'Plastic film and shrink wrap',
      'Thin packaging materials',
      'Plastic strapping',
      'Warehouse and logistics operations',
      '#daoantoanmartor #daoantoan #daocatantoan #martorchinhhang #daocongnghiep #daorocthung #daorocmangphim #daocatdai #luoidaomartor',
    ],
    applications: [
      'Cắt màng nhựa PE, PVC',
      'Cắt bao bì mỏng',
      'Cắt dây đai nhựa',
      'Sử dụng trong kho vận, logistics và dây chuyền đóng gói',
    ],
    images: [
      '/products/martor/secumax-145-145001-12-1.webp',
      '/products/martor/secumax-145-145001-12-2.webp',
      '/products/martor/secumax-145-145001-12-3.webp',
      '/products/martor/secumax-145-145001-12-4.webp',
    ],
    kw: ['dao an toan', 'martor', 'secumax 145'],
  },
  {
    part: '148001.12', name: 'SECUMAX 148', brand: 'martor', category: 'an-toan',
    series: 'SECUMAX', origin: 'Đức',
    desc: 'Dao an toàn MARTOR SECUMAX 148 No.148001.12 là dòng dao cắt bao bì an toàn chính hãng của MARTOR, được thiết kế chuyên dụng cho các môi trường làm việc yêu cầu mức độ an toàn cao như kho vận, logistics và dây chuyền sản xuất.',
    descFull: [
      'Dao an toàn MARTOR SECUMAX 148 No.148001.12 là dòng dao cắt bao bì an toàn chính hãng của MARTOR, được thiết kế chuyên dụng cho các môi trường làm việc yêu cầu mức độ an toàn cao như kho vận, logistics và dây chuyền sản xuất.',
      'Sản phẩm thuộc dòng SECUMAX, nổi bật với lưỡi cắt được che chắn hoàn toàn, giúp giảm thiểu tối đa nguy cơ tai nạn lao động và hạn chế làm hư hỏng hàng hóa trong quá trình thao tác.',
      'Dao có thiết kế nhỏ gọn, nhẹ và dễ sử dụng, giúp người dùng thao tác cắt nhanh và chính xác trên các vật liệu đóng gói mỏng.',
      'Ưu điểm nổi bật',
      'Lưỡi cắt được che kín hoàn toàn',
      'Thiết kế lưỡi ẩn giúp đảm bảo an toàn tối đa cho người sử dụng.',
      'Bảo vệ hàng hóa khi cắt',
      'Lưỡi dao nằm trong khe cắt giúp hạn chế làm rách hoặc hư hỏng sản phẩm bên trong bao bì.',
      'Thiết kế nhỏ gọn và nhẹ',
      'Giúp thao tác nhanh, linh hoạt và giảm mỏi tay khi làm việc liên tục.',
      'Chất liệu bền bỉ',
      'Thân dao được làm từ nhựa kỹ thuật cao cấp, có độ bền cao và chịu va đập tốt.',
      'Thông số kỹ thuật',
      'Model: SECUMAX 148 No.148001.12',
      'Dòng sản phẩm: SECUMAX 148',
      'Quy cách đóng gói: 10 cái / hộp',
      'Chất liệu thân dao: Nhựa kỹ thuật cao cấp',
      'Cơ chế an toàn: Lưỡi cắt che chắn cố định',
      'Xuất xứ: Đức',
      'Ứng dụng',
      'Cắt màng nhựa và màng film',
      'Cắt bao bì mỏng',
      'Cắt dây đai nhựa',
      'Sử dụng trong kho vận, logistics và nhà máy sản xuất',
      '---------------------',
      'The MARTOR SECUMAX 148 No.148001.12 is a professional safety cutter designed for packaging and warehouse operations. Manufactured by MARTOR (Germany), this tool is ideal for workplaces that require a high level of safety.',
      'The cutter features a fully concealed blade, which significantly reduces the risk of injury and helps protect packaged goods during cutting operations.',
      'Its compact and lightweight design makes it easy to handle and ideal for fast cutting of thin packaging materials.',
      'Key Features',
      'Fully concealed blade for maximum safety',
      'Protects goods during cutting',
      'Lightweight and compact design',
      'Durable high-quality plastic body',
      'Applications',
      'Plastic film and shrink wrap',
      'Thin packaging materials',
      'Plastic strapping',
      'Warehouse and logistics operations',
      '#daoantoanmartor #daoantoan #daocatantoan #martorchinhhang #daocongnghiep #daorocthung #daorocmangphim #daocatdai #luoidaomartor',
    ],
    applications: [
      'Cắt màng nhựa và màng film',
      'Cắt bao bì mỏng',
      'Cắt dây đai nhựa',
      'Sử dụng trong kho vận, logistics và nhà máy sản xuất',
    ],
    images: [
      '/products/martor/secumax-148-148001-12-1.webp',
      '/products/martor/secumax-148-148001-12-2.webp',
      '/products/martor/secumax-148-148001-12-3.webp',
      '/products/martor/secumax-148-148001-12-4.webp',
      '/products/martor/secumax-148-148001-12-5.webp',
    ],
    kw: ['dao an toan', 'martor', 'secumax 148'],
  },
  {
    part: '150001.12', name: 'SECUMAX 150', brand: 'martor', category: 'an-toan',
    series: 'SECUMAX', origin: 'Đức',
    desc: 'Dao an toàn MARTOR SECUMAX 150 No.150001.12 là dao cắt an toàn công nghiệp chính hãng của MARTOR, được thiết kế dành cho các môi trường làm việc yêu cầu tiêu chuẩn an toàn cao như kho vận, đóng gói và nhà máy sản xuất.',
    descFull: [
      'Dao an toàn MARTOR SECUMAX 150 No.150001.12 là dao cắt an toàn công nghiệp chính hãng của MARTOR, được thiết kế dành cho các môi trường làm việc yêu cầu tiêu chuẩn an toàn cao như kho vận, đóng gói và nhà máy sản xuất.',
      'Sản phẩm sử dụng cơ chế lưỡi cắt che chắn hoàn toàn (concealed blade) giúp bảo vệ tối đa người sử dụng và hạn chế nguy cơ làm hư hỏng hàng hóa khi thao tác. Thiết kế nhỏ gọn, trọng lượng nhẹ giúp người dùng thao tác nhanh và thoải mái trong các công việc cắt lặp lại hằng ngày.',
      'SECUMAX 150 là lựa chọn phù hợp cho các doanh nghiệp cần dụng cụ cắt an toàn, bền bỉ và hiệu quả trong môi trường công nghiệp.',
      'Ưu điểm nổi bật',
      'Lưỡi cắt che chắn hoàn toàn',
      'Giảm tối đa nguy cơ tai nạn lao động và bảo vệ hàng hóa khi cắt.',
      'Thiết kế nhỏ gọn – thao tác linh hoạt',
      'Trọng lượng nhẹ, dễ cầm nắm, phù hợp cho thao tác liên tục.',
      'Độ bền cao trong môi trường công nghiệp',
      'Thân dao bằng nhựa kỹ thuật cao cấp, chịu mài mòn tốt.',
      'Hiệu quả cho công việc cắt lặp lại',
      'Tối ưu cho công việc đóng gói, kho vận và sản xuất.',
      'Thông số kỹ thuật',
      'Model: SECUMAX 150',
      'Mã sản phẩm: No.150001.12',
      'Quy cách đóng gói: 10 cái / hộp',
      'Chất liệu thân dao: Nhựa kỹ thuật cao cấp',
      'Cơ chế an toàn: Lưỡi cắt che chắn cố định',
      'Xuất xứ: Đức',
      'Ứng dụng',
      'Cắt màng nhựa PE, PVC',
      'Cắt bao bì mỏng',
      'Cắt dây đai nhựa',
      'Sử dụng trong kho vận, logistics, dây chuyền đóng gói và nhà máy sản xuất',
      '---------------------',
      'The MARTOR SECUMAX 150 No.150001.12 is an industrial safety cutter designed for workplaces requiring high safety standards such as warehouses, packaging operations, and manufacturing facilities.',
      'This knife features a fully concealed blade, providing maximum protection for users while reducing the risk of damaging packaged goods during cutting tasks. Its lightweight and compact design ensures comfortable handling and efficient performance during repetitive cutting operations.',
      'The SECUMAX 150 is an ideal safety cutter for companies seeking reliable, durable, and safe cutting tools for industrial environments.',
      'Key Features',
      'Fully concealed blade for maximum safety',
      'Lightweight and ergonomic design',
      'Durable technical plastic body',
      'Ideal for repetitive packaging and warehouse cutting tasks',
      '#daoantoanmartor #daoantoan #daocatantoan #martorchinhhang #daocongnghiep #daorocthung #daorocmangphim #daocatdai #luoidaomartor',
    ],
    applications: [
      'Cắt màng nhựa PE, PVC',
      'Cắt bao bì mỏng',
      'Cắt dây đai nhựa',
      'Sử dụng trong kho vận, logistics, dây chuyền đóng gói và nhà máy sản xuất',
    ],
    images: [
      '/products/martor/secumax-150-150001-12-1.webp',
      '/products/martor/secumax-150-150001-12-2.webp',
      '/products/martor/secumax-150-150001-12-3.webp',
      '/products/martor/secumax-150-150001-12-4.webp',
      '/products/martor/secumax-150-150001-12-5.webp',
    ],
    kw: ['dao an toan', 'martor', 'secumax 150'],
  },
  {
    part: '121001.02', name: 'SECUMAX EASYSAFE', brand: 'martor', category: 'an-toan',
    series: 'SECUMAX', origin: 'Đức',
    desc: 'Dao an toàn MARTOR SECUMAX EASYSAFE No.121001.02 là dao cắt an toàn công nghiệp đến từ MARTOR, được thiết kế chuyên dụng cho các công việc cắt bao bì, dây đai, màng film và thùng carton trong môi trường kho vận và sản xuất.',
    descFull: [
      'Dao an toàn MARTOR SECUMAX EASYSAFE No.121001.02 là dao cắt an toàn công nghiệp đến từ MARTOR, được thiết kế chuyên dụng cho các công việc cắt bao bì, dây đai, màng film và thùng carton trong môi trường kho vận và sản xuất.',
      'Sản phẩm có lưỡi dao được giấu kín hoàn toàn, giúp giảm nguy cơ tai nạn lao động và hạn chế làm hư hỏng hàng hóa khi thao tác. Thiết kế nhỏ gọn, trọng lượng nhẹ giúp người dùng thao tác dễ dàng và thoải mái khi sử dụng liên tục.',
      'Thân dao được làm từ nhựa gia cố sợi thủy tinh, mang lại độ bền cao và khả năng chống mài mòn tốt trong môi trường công nghiệp.',
      'Ưu điểm nổi bật',
      'Thiết kế nhỏ gọn – trọng lượng nhẹ',
      'Trọng lượng chỉ khoảng 66.3 g, giúp thao tác cắt nhanh và ít gây mệt mỏi khi sử dụng lâu.',
      'Lưỡi dao ẩn an toàn',
      'Giảm nguy cơ bị thương và bảo vệ hàng hóa khi cắt.',
      'Lưỡi dao 4 cạnh cắt',
      'Có thể xoay lưỡi để sử dụng nhiều lần, kéo dài tuổi thọ lưỡi dao.',
      'Thay lưỡi dễ dàng',
      'Có thể thay lưỡi nhanh chóng mà không cần dụng cụ hỗ trợ.',
      'Thiết kế công thái học',
      'Tay cầm thuận tiện, phù hợp cho cả người thuận tay trái và tay phải.',
      'Thông số kỹ thuật',
      'Model: SECUMAX EASYSAFE',
      'Mã sản phẩm: No.121001.02',
      'Khối lượng: 66.3 g',
      'Độ sâu cắt: 6.6 mm',
      'Kích thước: 207 × 10 × 66 mm',
      'Chất liệu thân dao: Nhựa gia cố sợi thủy tinh',
      'Xuất xứ: Đức',
      'Ứng dụng',
      'Cắt dây đai nhựa',
      'Cắt màng film và bao bì nhựa',
      'Cắt thùng carton',
      'Sử dụng trong kho vận, logistics và dây chuyền đóng gói',
      '-----------------------',
      'The MARTOR SECUMAX EASYSAFE No.121001.02 is an industrial safety cutter designed for packaging and logistics applications.',
      'The knife features a fully concealed blade, ensuring maximum safety for the user while preventing damage to packaged goods. Its lightweight and ergonomic design makes it comfortable for continuous use.',
      'The body is made from glass-fiber reinforced plastic, providing durability and resistance to wear in industrial environments.',
      'Key Features',
      'Concealed blade for maximum safety',
      'Lightweight and ergonomic design',
      'Durable glass-fiber reinforced plastic body',
      'Four cutting edges for extended blade life',
      'Tool-free blade replacement',
      '#daoantoanmartor #daoantoan #daocatantoan #martorchinhhang #daocongnghiep #daorocthung #daorocmangphim #daocatdai #luoidaomartor',
    ],
    applications: [
      'Cắt dây đai nhựa',
      'Cắt màng film và bao bì nhựa',
      'Cắt thùng carton',
      'Sử dụng trong kho vận, logistics và dây chuyền đóng gói',
    ],
    images: [
      '/products/martor/secumax-easysafe-121001-02-1.webp',
      '/products/martor/secumax-easysafe-121001-02-2.webp',
      '/products/martor/secumax-easysafe-121001-02-3.webp',
      '/products/martor/secumax-easysafe-121001-02-4.webp',
      '/products/martor/secumax-easysafe-121001-02-5.webp',
    ],
    kw: ['dao an toan', 'martor', 'secumax easysafe'],
  },
  {
    part: '125002.02', name: 'SECUNORM MIZAR', brand: 'martor', category: 'an-toan',
    series: 'SECUNORM', origin: 'Đức',
    desc: 'MARTOR SECUNORM MIZAR No.125002.02 là dao an toàn đa năng với cơ chế lưỡi tự động thu hồi, giúp lưỡi rút vào thân ngay khi người dùng nhả cần gạt.',
    descFull: [
      'MARTOR SECUNORM MIZAR No.125002.02 là dao an toàn đa năng với cơ chế lưỡi tự động thu hồi, giúp lưỡi rút vào thân ngay khi người dùng nhả cần gạt. Thân dao làm từ nhựa tái chế kết hợp nhựa gia cường sợi thủy tinh, bền và phù hợp cho tần suất sử dụng cao. Phiên bản No.125002.02 lắp TRAPEZOID BLADE No.65232 có đầu lưỡi bo tròn, giúp tăng mức độ an toàn khi thao tác và có độ sâu cắt tối đa 13 mm.',
      'Thông số chính:',
      '- Model: SECUNORM MIZAR No.125002.02',
      '- Kích thước: 139 × 15.6 × 50.5 mm',
      '- Trọng lượng: 55 g',
      '- Độ sâu cắt tối đa: 13 mm',
      '- Lưỡi lắp sẵn: TRAPEZOID BLADE No.65232, đầu bo tròn',
      '- Cơ chế an toàn: Lưỡi tự động thu hồi',
      'ENGLISH',
      'The MARTOR SECUNORM MIZAR No.125002.02 is a versatile safety knife with automatic blade retraction. Releasing the lever allows the blade to retract into the handle, helping improve user safety. The durable handle combines recycled plastic and glass-fibre-reinforced plastic for frequent industrial use. This version is fitted with rounded-tip TRAPEZOID BLADE No.65232 and provides a maximum cutting depth of 13 mm.',
      'Key specifications:',
      '- Model: SECUNORM MIZAR No.125002.02',
      '- Dimensions: 139 × 15.6 × 50.5 mm',
      '- Weight: 55 g',
      '- Max. cutting depth: 13 mm',
      '- Installed blade: Rounded-tip TRAPEZOID BLADE No.65232',
      '- Safety system: Automatic blade retraction',
      '#daoantoanmartor #daoantoan #daocatantoan #martorchinhhang #daocongnghiep #daorocthung #daorocmangphim #daocatdai #luoidaomartor',
    ],
    applications: [
      'Cắt carton và bao bì đóng gói',
      'Cắt film, màng co và màng stretch',
      'Cắt băng keo, vật liệu lớp và dây đai đóng gói',
      'Phù hợp kho xưởng, logistics và dây chuyền sản xuất',
    ],
    images: [
      '/products/martor/secunorm-mizar-125002-02-1.webp',
      '/products/martor/secunorm-mizar-125002-02-2.webp',
      '/products/martor/secunorm-mizar-125002-02-3.webp',
      '/products/martor/secunorm-mizar-125002-02-4.webp',
      '/products/martor/secunorm-mizar-125002-02-5.webp',
    ],
    docUrl: 'https://martor.com/en-US/p/secunorm-mizar-125002',
    kw: ['dao an toan', 'martor', 'secunorm mizar'],
  },
  {
    part: '120701.02', name: 'SECUNORM PROFI25 MDP', brand: 'martor', category: 'an-toan',
    series: 'SECUNORM', origin: 'Đức',
    desc: 'Dao an toàn MARTOR SECUNORM PROFI25 MDP No.120701.02 là dao cắt an toàn công nghiệp chính hãng của MARTOR, được thiết kế với thân dao bằng nhựa MDP (Metal Detectable Plastic) có khả năng phát hiện kim loại, phù hợp cho các môi…',
    descFull: [
      'Dao an toàn MARTOR SECUNORM PROFI25 MDP No.120701.02 là dao cắt an toàn công nghiệp chính hãng của MARTOR, được thiết kế với thân dao bằng nhựa MDP (Metal Detectable Plastic) có khả năng phát hiện kim loại, phù hợp cho các môi trường yêu cầu kiểm soát an toàn nghiêm ngặt.',
      'Dao được trang bị cơ chế lưỡi tự động thu hồi, giúp lưỡi dao rút lại ngay khi rời khỏi vật liệu cắt, từ đó giảm thiểu tối đa nguy cơ tai nạn lao động. Nhờ đặc tính phát hiện kim loại, sản phẩm đặc biệt phù hợp cho ngành thực phẩm, dược phẩm, phòng sạch và các dây chuyền sản xuất yêu cầu tiêu chuẩn an toàn cao.',
      'Thiết kế chắc chắn và công thái học giúp người dùng thao tác cắt thùng carton, bao bì, màng nhựa và vật liệu đóng gói một cách hiệu quả và an toàn.',
      'Ưu điểm nổi bật',
      'Nhựa MDP phát hiện kim loại',
      'Phù hợp cho ngành thực phẩm, dược phẩm và môi trường HACCP.',
      'Cơ chế tự động thu hồi lưỡi',
      'Giúp tăng mức độ an toàn khi thao tác cắt.',
      'Thiết kế chắc chắn, công thái học',
      'Cầm nắm thoải mái và dễ kiểm soát khi sử dụng liên tục.',
      'Hiệu suất cắt ổn định',
      'Phù hợp cho các công việc cắt bao bì và vật liệu đóng gói.',
      'Thông số kỹ thuật',
      'Model: 120701.02',
      'Dòng sản phẩm: SECUNORM PROFI25 MDP',
      'Chất liệu thân dao: Nhựa MDP (Metal Detectable Plastic)',
      'Cơ chế an toàn: Lưỡi tự động thu hồi',
      'Xuất xứ: Đức',
      'Ứng dụng',
      'Cắt thùng carton và bao bì',
      'Cắt màng nhựa và vật liệu đóng gói',
      'Sử dụng trong ngành thực phẩm, dược phẩm, phòng sạch',
      'Ứng dụng trong kho vận, logistics và sản xuất công nghiệp',
      '---------------------------',
      'The MARTOR SECUNORM PROFI25 MDP No.120701.02 is an original industrial safety knife designed by MARTOR (Germany). The knife features a metal-detectable plastic (MDP) handle, making it suitable for environments where strict safety and contamination control are required.',
      'Equipped with an automatic blade retraction mechanism, the blade retracts immediately once it leaves the cutting material, significantly reducing the risk of injuries.',
      'Thanks to its metal-detectable material, the knife is ideal for food processing, pharmaceutical production, cleanrooms, and other safety-critical manufacturing environments.',
      'It provides reliable performance for cutting cardboard boxes, plastic film, and packaging materials in industrial operations.',
      'Key Features',
      'Metal detectable plastic (MDP) handle',
      'Automatic blade retraction for enhanced safety',
      'Durable and ergonomic design',
      'Reliable cutting performance for packaging materials',
      'Ideal for food, pharmaceutical, and cleanroom industries',
      '#daoantoanmartor #daoantoan #daocatantoan #martorchinhhang #daocongnghiep #daorocthung #daorocmangphim #daocatdai #luoidaomartor',
    ],
    applications: [
      'Cắt thùng carton và bao bì',
      'Cắt màng nhựa và vật liệu đóng gói',
      'Sử dụng trong ngành thực phẩm, dược phẩm, phòng sạch',
      'Ứng dụng trong kho vận, logistics và sản xuất công nghiệp',
    ],
    images: [
      '/products/martor/secunorm-profi25-mdp-120701-02-1.webp',
      '/products/martor/secunorm-profi25-mdp-120701-02-2.webp',
      '/products/martor/secunorm-profi25-mdp-120701-02-3.webp',
      '/products/martor/secunorm-profi25-mdp-120701-02-4.webp',
    ],
    kw: ['dao an toan', 'martor', 'secunorm profi25 mdp'],
  },
  {
    part: '11900771.02', name: 'SECUNORM PROFI40', brand: 'martor', category: 'an-toan',
    series: 'SECUNORM', origin: 'Đức',
    desc: 'Dao an toàn MARTOR SECUNORM PROFI40 No.11900771.02 là dòng dao cắt an toàn công nghiệp chuyên nghiệp của MARTOR, được thiết kế cho các công việc cắt nặng trong kho vận, logistics và nhà máy sản xuất.',
    descFull: [
      'Dao an toàn MARTOR SECUNORM PROFI40 No.11900771.02 là dòng dao cắt an toàn công nghiệp chuyên nghiệp của MARTOR, được thiết kế cho các công việc cắt nặng trong kho vận, logistics và nhà máy sản xuất.',
      'Sản phẩm được trang bị cơ chế lưỡi tự động thu hồi (automatic blade retraction). Khi người dùng nhả thanh trượt, lưỡi dao sẽ tự động rút vào thân dao, giúp giảm nguy cơ tai nạn lao động và tăng độ an toàn khi thao tác.',
      'SECUNORM PROFI40 sở hữu thân dao kim loại chắc chắn, mang lại độ bền cao và khả năng chịu lực tốt trong môi trường công nghiệp. Thiết kế công thái học giúp người dùng cầm nắm chắc chắn và kiểm soát tốt khi thực hiện các thao tác cắt liên tục.',
      'Ưu điểm nổi bật',
      'Cơ chế lưỡi tự động thu hồi',
      'Lưỡi dao tự động rút vào thân sau khi cắt, giúp tăng mức độ an toàn cho người sử dụng.',
      'Thân dao kim loại bền bỉ',
      'Chất liệu hợp kim chắc chắn giúp dao chịu lực tốt trong các công việc cắt nặng.',
      'Thiết kế công thái học',
      'Tay cầm được tối ưu để cầm nắm chắc chắn và thao tác dễ dàng.',
      'Hiệu suất cắt mạnh mẽ',
      'Phù hợp cho các vật liệu đóng gói dày và công việc cắt công nghiệp thường xuyên.',
      'Thông số kỹ thuật',
      'Model: SECUNORM PROFI40 No.11900771.02',
      'Dòng sản phẩm: SECUNORM PROFI40',
      'Chất liệu thân dao: Kim loại (hợp kim)',
      'Cơ chế an toàn: Lưỡi tự động thu hồi',
      'Xuất xứ: Đức (Germany)',
      'Ứng dụng',
      'Cắt thùng carton dày',
      'Cắt bao bì công nghiệp',
      'Cắt dây đai đóng gói',
      'Cắt vật liệu đóng gói trong kho vận và logistics',
      'Sử dụng trong nhà máy sản xuất và dây chuyền đóng gói',
      '-----------',
      'The MARTOR SECUNORM PROFI40 No.11900771.02 is a professional industrial safety knife designed for demanding cutting tasks in warehouses, logistics operations, and manufacturing facilities.',
      'Manufactured by MARTOR (Germany), the knife features an automatic blade retraction mechanism, ensuring the blade retracts immediately after the slider is released. This significantly improves user safety and reduces the risk of injuries.',
      'The cutter is built with a durable metal alloy handle, providing excellent strength and reliability for heavy-duty industrial applications. Its ergonomic design ensures comfortable handling and precise control during continuous cutting operations.',
      'Key Features',
      'Automatic blade retraction for enhanced safety',
      'Durable metal alloy handle for industrial use',
      'Ergonomic design for comfortable handling',
      'Reliable cutting performance for heavy-duty materials',
      'Applications',
      'Cutting thick cardboard boxes',
      'Industrial packaging materials',
      'Plastic strapping and wrapping',
      'Warehouse and logistics operations',
      '#daoantoanmartor #daoantoan #daocatantoan #martorchinhhang #daocongnghiep #daorocthung #daorocmangphim #daocatdai #luoidaomartor',
    ],
    applications: [
      'Cắt thùng carton dày',
      'Cắt bao bì công nghiệp',
      'Cắt dây đai đóng gói',
      'Cắt vật liệu đóng gói trong kho vận và logistics',
      'Sử dụng trong nhà máy sản xuất và dây chuyền đóng gói',
    ],
    images: [
      '/products/martor/secunorm-profi40-11900771-02-1.webp',
      '/products/martor/secunorm-profi40-11900771-02-2.webp',
      '/products/martor/secunorm-profi40-11900771-02-3.webp',
      '/products/martor/secunorm-profi40-11900771-02-4.webp',
    ],
    kw: ['dao an toan', 'martor', 'secunorm profi40'],
  },
  {
    part: '110000.02', name: 'SECUNORM SMARTCUT', brand: 'martor', category: 'an-toan',
    series: 'SECUNORM', origin: 'Đức',
    desc: 'MARTOR SECUNORM SMARTCUT No.110000.02 là dao an toàn dùng một lần, nhỏ gọn và nhẹ, phù hợp cho các công việc cắt bao bì thường xuyên trong kho vận, sản xuất và đóng gói.',
    descFull: [
      'MARTOR SECUNORM SMARTCUT No.110000.02 là dao an toàn dùng một lần, nhỏ gọn và nhẹ, phù hợp cho các công việc cắt bao bì thường xuyên trong kho vận, sản xuất và đóng gói. Dao sử dụng cơ chế lưỡi tự động thu hồi: sau khi bắt đầu đường cắt và người dùng nhả thanh trượt, lưỡi dao sẽ rút vào thân ngay khi rời vật liệu, giúp giảm nguy cơ bị cắt. Thiết kế thanh trượt hai bên thuận tiện cho cả người thuận tay trái và tay phải.',
      'Thông số chính:',
      '- Model: SECUNORM SMARTCUT No.110000.02',
      '- Kích thước: 110 × 12.5 × 25 mm',
      '- Trọng lượng: 17.2 g',
      '- Độ sâu cắt tối đa: 11.6 mm',
      '- Vật liệu thân: Nhựa',
      '- Cơ chế an toàn: Lưỡi tự động thu hồi',
      'ENGLISH',
      'The MARTOR SECUNORM SMARTCUT No.110000.02 is a compact, lightweight disposable safety knife designed for routine packaging and warehouse cutting tasks. Its automatic blade retraction system allows the blade to retract into the handle as soon as it leaves the cutting material after the slider is released, helping reduce cut injuries. The double-sided slider supports convenient use by both right- and left-handed operators.',
      'Key specifications:',
      '- Model: SECUNORM SMARTCUT No.110000.02',
      '- Dimensions: 110 × 12.5 × 25 mm',
      '- Weight: 17.2 g',
      '- Max. cutting depth: 11.6 mm',
      '- Handle material: Plastic',
      '- Safety system: Automatic blade retraction',
      '#daoantoanmartor #daoantoan #daocatantoan #martorchinhhang #daocongnghiep #daorocthung #daorocmangphim #daocatdai #luoidaomartor',
    ],
    applications: [
      'Cắt màng co, màng stretch và film đóng gói',
      'Cắt giấy, lớp màng và bao bì mỏng',
      'Mở thùng carton và cắt băng keo',
      'Sử dụng tại kho, dây chuyền đóng gói và logistics',
    ],
    images: [
      '/products/martor/secunorm-smartcut-110000-02-1.webp',
      '/products/martor/secunorm-smartcut-110000-02-2.webp',
      '/products/martor/secunorm-smartcut-110000-02-3.webp',
    ],
    docUrl: 'https://martor.com/en-DE/p/secunorm-smartcut-110000',
    kw: ['dao an toan', 'martor', 'secunorm smartcut'],
  },
  {
    part: '110700.02', name: 'SECUNORM SMARTCUT MDP', brand: 'martor', category: 'an-toan',
    series: 'SECUNORM', origin: 'Đức',
    desc: 'Dao an toàn MARTOR SECUNORM SMARTCUT MDP No.110700.02 là dòng dao cắt an toàn chuyên dụng của MARTOR, được thiết kế cho các môi trường sản xuất yêu cầu tiêu chuẩn an toàn và kiểm soát dị vật nghiêm ngặt như ngành thực phẩm, dược…',
    descFull: [
      'Dao an toàn MARTOR SECUNORM SMARTCUT MDP No.110700.02 là dòng dao cắt an toàn chuyên dụng của MARTOR, được thiết kế cho các môi trường sản xuất yêu cầu tiêu chuẩn an toàn và kiểm soát dị vật nghiêm ngặt như ngành thực phẩm, dược phẩm và phòng sạch.',
      'Thân dao được chế tạo từ nhựa MDP (Metal Detectable Plastic) – vật liệu có khả năng phát hiện bằng máy dò kim loại, giúp giảm nguy cơ lẫn dị vật trong dây chuyền sản xuất và đáp ứng các tiêu chuẩn HACCP.',
      'Sản phẩm được trang bị cơ chế lưỡi tự động thu hồi, đảm bảo lưỡi dao rút lại ngay sau khi thao tác cắt, giúp giảm thiểu rủi ro tai nạn lao động và tăng độ an toàn khi sử dụng.',
      'Với thiết kế nhỏ gọn, linh hoạt và dễ kiểm soát, SECUNORM SMARTCUT MDP là lựa chọn phù hợp cho các công việc cắt bao bì, màng nhựa và thùng carton mỏng trong môi trường sản xuất hiện đại.',
      'Ưu điểm nổi bật',
      'Cơ chế lưỡi tự động thu hồi',
      'Lưỡi dao tự động rút vào thân sau khi cắt, giúp tăng độ an toàn cho người sử dụng.',
      'Nhựa MDP phát hiện kim loại',
      'Thân dao có thể được phát hiện bởi hệ thống dò kim loại trong dây chuyền sản xuất.',
      'Phù hợp tiêu chuẩn HACCP',
      'Lý tưởng cho các ngành yêu cầu kiểm soát vệ sinh nghiêm ngặt như thực phẩm và dược phẩm.',
      'Thiết kế nhỏ gọn, linh hoạt',
      'Giúp thao tác cắt nhanh và chính xác trong môi trường làm việc chuyên nghiệp.',
      'Thông số kỹ thuật',
      'Model: SECUNORM SMARTCUT MDP No.110700.02',
      'Dòng sản phẩm: SECUNORM SMARTCUT MDP',
      'Chất liệu thân dao: Nhựa MDP (Metal Detectable Plastic)',
      'Cơ chế an toàn: Lưỡi tự động thu hồi',
      'Xuất xứ: Đức (Germany)',
      'Ứng dụng',
      'Cắt bao bì đóng gói',
      'Cắt màng nhựa và màng film',
      'Cắt thùng carton mỏng',
      'Sử dụng trong ngành thực phẩm, dược phẩm và phòng sạch',
      'Ứng dụng trong kho vận, logistics và dây chuyền đóng gói',
      '--------------',
      'The MARTOR SECUNORM SMARTCUT MDP No.110700.02 is a professional safety knife designed for environments requiring strict safety and contamination control, such as food processing, pharmaceutical production, and cleanroom environments.',
      'Manufactured by MARTOR (Germany), the knife features a Metal Detectable Plastic (MDP) body, allowing it to be detected by metal detection systems used in modern production lines. This helps reduce contamination risks and supports HACCP compliance.',
      'The knife also features an automatic blade retraction mechanism, ensuring the blade retracts immediately after cutting, improving workplace safety.',
      'Its compact and ergonomic design allows efficient and precise cutting of packaging materials, plastic film, and thin cardboard.',
      'Key Features',
      'Automatic blade retraction for improved safety',
      'Metal detectable plastic body for HACCP compliance',
      'Compact and ergonomic design',
      'Ideal for hygiene-sensitive production environments',
      'Applications',
      'Packaging materials and plastic film',
      'Thin cardboard cutting',
      'Food processing industry',
      'Pharmaceutical manufacturing',
      'Cleanroom environments',
      '#daoantoanmartor #daoantoan #daocatantoan #martorchinhhang #daocongnghiep #daorocthung #daorocmangphim #daocatdai #luoidaomartor',
    ],
    applications: [
      'Cắt bao bì đóng gói',
      'Cắt màng nhựa và màng film',
      'Cắt thùng carton mỏng',
      'Sử dụng trong ngành thực phẩm, dược phẩm và phòng sạch',
      'Ứng dụng trong kho vận, logistics và dây chuyền đóng gói',
    ],
    images: [
      '/products/martor/secunorm-smartcut-mdp-110700-02-1.webp',
    ],
    docPdf: '/catalogs/martor/secunorm-smartcut-mdp-110700-02.pdf',
    kw: ['dao an toan', 'martor', 'secunorm smartcut mdp'],
  },
  {
    part: '122001.02', name: 'SECUPRO MARTEGO', brand: 'martor', category: 'an-toan',
    series: 'SECUPRO', origin: 'Đức',
    desc: 'Dao an toàn MARTOR SECUPRO MARTEGO No.122001.02 là dao cắt an toàn công nghiệp cao cấp của MARTOR, nổi bật với cơ chế bóp tay cầm và tự động rút lưỡi hoàn toàn, giúp tăng mức độ an toàn cho người sử dụng và bảo vệ hàng hóa khi…',
    descFull: [
      'Dao an toàn MARTOR SECUPRO MARTEGO No.122001.02 là dao cắt an toàn công nghiệp cao cấp của MARTOR, nổi bật với cơ chế bóp tay cầm và tự động rút lưỡi hoàn toàn, giúp tăng mức độ an toàn cho người sử dụng và bảo vệ hàng hóa khi cắt.',
      'SECUPRO MARTEGO được thiết kế cho môi trường làm việc chuyên nghiệp như kho vận, logistics, dây chuyền đóng gói và nhà máy sản xuất. Cấu trúc chắc chắn cùng thiết kế công thái học giúp thao tác cắt ổn định, giảm mỏi tay khi sử dụng trong thời gian dài.',
      'Dao sử dụng lưỡi dao công nghiệp tiêu chuẩn Solingen, có 4 cạnh cắt sắc bén, cho phép xoay lưỡi để kéo dài thời gian sử dụng và tối ưu chi phí vận hành.',
      'Ưu điểm nổi bật',
      'Thiết kế an toàn vượt trội',
      'Cơ chế bóp tay cầm – tự động rút lưỡi hoàn toàn',
      'Lưỡi dao chỉ lộ ra khi thao tác cắt',
      'Khóa bảo vệ an toàn giúp tránh bật lưỡi ngoài ý muốn',
      'Nam châm tích hợp giữ lưỡi dao chắc chắn khi thay lưỡi',
      'Thay lưỡi nhanh – không cần dụng cụ',
      'Cơ chế thay lưỡi đơn giản, thao tác nhanh chóng, phù hợp môi trường kho xưởng và dây chuyền đóng gói.',
      'Lưỡi dao công nghiệp chất lượng cao',
      'Lưỡi dao thép Solingen – Đức',
      '4 cạnh cắt sắc bén, có thể xoay để sử dụng nhiều lần',
      'Độ sâu cắt 9 mm giúp cắt hiệu quả mà vẫn bảo vệ hàng hóa',
      'Thiết kế công thái học',
      'Tay cầm kim loại chắc chắn',
      'Phù hợp cho cả người thuận tay trái và tay phải',
      'Cầm nắm toải mái khi sử dụng liên tục',
      'Thông số kỹ thuật',
      'Model: SECUPRO MARTEGO',
      'Mã sản phẩm: No.122001.02',
      'Cơ chế an toàn: Tự động thu hồi lưỡi',
      'Độ sâu cắt: 9 mm',
      'Khối lượng: 104 g',
      'Kích thước: 155 × 18 × 48.5 mm',
      'Xuất xứ: Đức',
      'Ứng dụng',
      'Cắt thùng carton',
      'Cắt màng nhựa và bao bì',
      'Cắt băng keo, dây đai đóng gói',
      'Sử dụng trong kho vận, logistics, nhà máy sản xuất',
      '----------------',
      'The MARTOR SECUPRO MARTEGO No.122001.02 is a premium industrial safety knife designed and manufactured by MARTOR in Germany. It features a fully automatic blade retraction mechanism activated by a squeeze handle, providing maximum safety for both the user and the goods being cut.',
      'Designed for professional use in warehouses, packaging lines, and industrial environments, the knife offers reliable cutting performance with an ergonomic design that reduces hand fatigue during continuous operation.',
      'The knife uses high-quality Solingen steel blades with four cutting edges, allowing the blade to be rotated to extend service life and reduce replacement frequency.',
      'Key Features',
      'Fully automatic blade retraction for maximum safety',
      'Ergonomic squeeze-handle design',
      'High-quality Solingen steel blade',
      'Four cutting edges for longer blade life',
      'Durable metal handle for industrial use',
      '#daoantoanmartor #daoantoan #daocatantoan #martorchinhhang #daocongnghiep #daorocthung #daorocmangphim #daocatdai #luoidaomartor',
    ],
    applications: [
      'Cắt thùng carton',
      'Cắt màng nhựa và bao bì',
      'Cắt băng keo, dây đai đóng gói',
      'Sử dụng trong kho vận, logistics, nhà máy sản xuất',
    ],
    images: [
      '/products/martor/secupro-martego-122001-02-1.webp',
      '/products/martor/secupro-martego-122001-02-2.webp',
      '/products/martor/secupro-martego-122001-02-3.webp',
      '/products/martor/secupro-martego-122001-02-4.webp',
    ],
    kw: ['dao an toan', 'martor', 'secupro martego'],
  },
  {
    part: '10130610', name: 'SECUPRO MAXISAFE', brand: 'martor', category: 'an-toan',
    series: 'SECUPRO', origin: 'Đức',
    desc: 'Dao cắt an toàn MARTOR SECUPRO MAXISAFE No.10130610 là dòng dao an toàn công nghiệp chính hãng của MARTOR, được thiết kế cho các công việc cắt bao bì và vật liệu đóng gói trong môi trường kho vận, logistics và dây chuyền sản xuất.',
    descFull: [
      'Dao cắt an toàn MARTOR SECUPRO MAXISAFE No.10130610 là dòng dao an toàn công nghiệp chính hãng của MARTOR, được thiết kế cho các công việc cắt bao bì và vật liệu đóng gói trong môi trường kho vận, logistics và dây chuyền sản xuất.',
      'Sản phẩm được trang bị cơ chế lưỡi dao tự động thu hồi hoàn toàn, giúp lưỡi dao rút vào thân ngay khi người dùng nhả thanh trượt. Điều này giúp tăng mức độ an toàn cho người sử dụng và bảo vệ hàng hóa trong quá trình cắt.',
      'SECUPRO MAXISAFE có thiết kế công thái học giúp thao tác cắt dễ dàng và linh hoạt. Dao có thể sử dụng cho nhiều kiểu cắt khác nhau và phù hợp với nhiều loại vật liệu đóng gói.',
      'Ưu điểm nổi bật',
      'Lưỡi dao tự động thu hồi',
      'Hệ thống an toàn giúp lưỡi dao rút vào thân ngay sau khi cắt, giảm nguy cơ tai nạn lao động.',
      'Thiết kế công thái học',
      'Tay cầm được thiết kế vừa vặn với bàn tay, giúp thao tác cắt thoải mái và chính xác.',
      'Đa năng trong ứng dụng cắt',
      'Có thể sử dụng để cắt nhiều loại vật liệu đóng gói khác nhau trong môi trường công nghiệp.',
      'Hiệu suất cắt ổn định',
      'Độ sâu cắt lớn giúp cắt dễ dàng carton, giấy và các vật liệu đóng gói dày.',
      'Thông số kỹ thuật',
      'Model: SECUPRO MAXISAFE No.10130610',
      'Trọng lượng: 66 g',
      'Độ sâu cắt: 16 mm',
      'Kích thước: 148 × 18 × 42 mm',
      'Cơ chế an toàn: Lưỡi tự động thu hồi',
      'Xuất xứ: Đức',
      'Ứng dụng',
      'Cắt màng film và màng nhựa',
      'Cắt giấy và bao bì đóng gói',
      'Cắt thùng carton 2 lớp',
      'Tách băng keo đóng gói',
      'Sử dụng trong kho xưởng, logistics và nhà máy sản xuất',
      '-------------------',
      'The MARTOR SECUPRO MAXISAFE No.10130610 is a professional safety knife designed for industrial packaging and warehouse applications. Manufactured by MARTOR (Germany), this cutter offers high safety and reliable cutting performance.',
      'The knife features a fully automatic blade retraction mechanism, ensuring that the blade retracts into the handle immediately when the slider is released. This significantly reduces the risk of injury and protects packaged goods.',
      'Its ergonomic design allows comfortable handling and versatile cutting applications.',
      'Key Features',
      'Fully automatic blade retraction for maximum safety',
      'Ergonomic handle for comfortable operation',
      'Suitable for multiple cutting styles',
      'Reliable cutting performance for packaging materials',
      'Applications',
      'Plastic film and shrink wrap',
      'Paper and packaging materials',
      'Double-wall carton cutting',
      'Packaging tape removal',
      'Warehouse and logistics operations',
      '#daoantoanmartor #daoantoan #daocatantoan #martorchinhhang #daocongnghiep #daorocthung #daorocmangphim #daocatdai #luoidaomartor',
    ],
    applications: [
      'Cắt màng film và màng nhựa',
      'Cắt giấy và bao bì đóng gói',
      'Cắt thùng carton 2 lớp',
      'Tách băng keo đóng gói',
      'Sử dụng trong kho xưởng, logistics và nhà máy sản xuất',
    ],
    images: [
      '/products/martor/secupro-maxisafe-10130610-1.webp',
      '/products/martor/secupro-maxisafe-10130610-2.webp',
      '/products/martor/secupro-maxisafe-10130610-3.webp',
    ],
    docPdf: '/catalogs/martor/secupro-maxisafe-10130610.pdf',
    kw: ['dao an toan', 'martor', 'secupro maxisafe'],
  },
  {
    part: '116001.02', name: 'SECUPRO MEGASAFE', brand: 'martor', category: 'an-toan',
    series: 'SECUPRO', origin: 'Đức',
    desc: 'Dao an toàn MARTOR SECUPRO MEGASAFE No.116001.02 là dao cắt an toàn công nghiệp cao cấp đến từ MARTOR, được thiết kế để đáp ứng các tiêu chuẩn an toàn cao trong môi trường kho vận, đóng gói và sản xuất công nghiệp.',
    descFull: [
      'Dao an toàn MARTOR SECUPRO MEGASAFE No.116001.02 là dao cắt an toàn công nghiệp cao cấp đến từ MARTOR, được thiết kế để đáp ứng các tiêu chuẩn an toàn cao trong môi trường kho vận, đóng gói và sản xuất công nghiệp.',
      'Sản phẩm sử dụng cơ chế tự động thu hồi lưỡi hoàn toàn (fully automatic blade retraction), giúp lưỡi dao rút vào thân ngay khi rời khỏi vật liệu cắt, từ đó giảm thiểu tối đa nguy cơ tai nạn lao động.',
      'SECUPRO MEGASAFE có thiết kế chắc chắn, công thái học, mang lại cảm giác cầm nắm thoải mái và kiểm soát tốt trong quá trình làm việc. Đây là lựa chọn lý tưởng cho các công việc cắt thùng carton, bao bì công nghiệp, màng nhựa và dây đai đóng gói.',
      'Ưu điểm nổi bật',
      'Cơ chế tự động thu hồi lưỡi hoàn toàn',
      'Lưỡi dao rút vào thân ngay khi rời vật cắt, tăng mức độ an toàn khi sử dụng.',
      'Thiết kế công thái học',
      'Cầm nắm chắc chắn, thao tác nhẹ nhàng trong quá trình làm việc liên tục.',
      'Hiệu quả trong môi trường công nghiệp',
      'Phù hợp cho công việc cắt bao bì, carton và vật liệu đóng gói.',
      'Chất lượng Đức – độ bền cao',
      'Sản phẩm chính hãng MARTOR, đảm bảo độ bền và độ ổn định khi sử dụng lâu dài.',
      'Thông số kỹ thuật',
      'Model: SECUPRO MEGASAFE',
      'Mã sản phẩm: No.116001.02',
      'Cơ chế an toàn: Lưỡi tự động thu hồi hoàn toàn',
      'Chất liệu thân dao: Nhựa kỹ thuật cao cấp',
      'Xuất xứ: Đức',
      'Ứng dụng',
      'Cắt thùng carton nhiều lớp',
      'Cắt bao bì công nghiệp',
      'Cắt màng nhựa, film đóng gói',
      'Cắt dây đai nhựa',
      'Sử dụng trong kho vận, logistics và nhà máy sản xuất',
      '----------------',
      'The MARTOR SECUPRO MEGASAFE No.116001.02 is a premium industrial safety knife designed for safe and efficient cutting in warehouses, packaging operations, and manufacturing environments.',
      'It features a fully automatic blade retraction mechanism, which retracts the blade immediately after leaving the cutting material, significantly reducing the risk of workplace injuries.',
      'The knife’s ergonomic and durable design ensures comfortable handling and reliable performance during intensive cutting tasks such as carton cutting, packaging materials, plastic film, and straps.',
      'Key Features',
      'Fully automatic blade retraction for maximum safety',
      'Ergonomic and durable design',
      'Reliable performance for industrial cutting tasks',
      'Ideal for cartons, packaging materials, film, and straps',
      '#daoantoanmartor #daoantoan #daocatantoan #martorchinhhang #daocongnghiep #daorocthung #daorocmangphim #daocatdai #luoidaomartor',
    ],
    applications: [
      'Cắt thùng carton nhiều lớp',
      'Cắt bao bì công nghiệp',
      'Cắt màng nhựa, film đóng gói',
      'Cắt dây đai nhựa',
      'Sử dụng trong kho vận, logistics và nhà máy sản xuất',
    ],
    images: [
      '/products/martor/secupro-megasafe-116001-02-1.webp',
      '/products/martor/secupro-megasafe-116001-02-2.webp',
      '/products/martor/secupro-megasafe-116001-02-3.webp',
    ],
    docPdf: '/catalogs/martor/secupro-megasafe-116001-02.pdf',
    kw: ['dao an toan', 'martor', 'secupro megasafe'],
  },
  {
    part: '124001', name: 'SECUPRO MERAK', brand: 'martor', category: 'an-toan',
    series: 'SECUPRO', origin: 'Đức',
    desc: 'Dao cắt an toàn MARTOR SECUPRO MERAK No.124001 là dòng dao an toàn công nghiệp cao cấp của MARTOR, được thiết kế theo cơ chế bóp (squeeze-grip) giúp thao tác cắt nhanh, chính xác và an toàn.',
    descFull: [
      'Dao cắt an toàn MARTOR SECUPRO MERAK No.124001 là dòng dao an toàn công nghiệp cao cấp của MARTOR, được thiết kế theo cơ chế bóp (squeeze-grip) giúp thao tác cắt nhanh, chính xác và an toàn.',
      'SECUPRO MERAK được xem như phiên bản nhỏ gọn và thân thiện hơn của dòng SECUPRO MARTEGO, mang lại sự thoải mái khi sử dụng nhưng vẫn đảm bảo hiệu suất cắt mạnh mẽ. Dao sử dụng cơ chế lưỡi tự động thu hồi hoàn toàn, khi nhả cần gạt lưỡi dao sẽ tự động rút vào thân dao, giúp giảm nguy cơ tai nạn lao động.',
      'Thiết kế độ sâu cắt vừa phải giúp bảo vệ hàng hóa bên trong thùng carton hoặc bao bì, đặc biệt phù hợp cho các công việc cắt trong kho vận, logistics, đóng gói và dây chuyền sản xuất công nghiệp.',
      'Ưu điểm nổi bật',
      'Cơ chế bóp công thái học',
      'Thiết kế squeeze-grip giúp thao tác cắt nhanh và thoải mái, giảm lực tay khi làm việc liên tục.',
      'Lưỡi dao tự động thu hồi',
      'Hệ thống an toàn giúp lưỡi dao tự động rút vào thân khi nhả cần gạt, tăng mức độ an toàn khi sử dụng.',
      'Thay lưỡi nhanh không cần dụng cụ',
      'Thiết kế thông minh cho phép thay lưỡi dễ dàng, nam châm tích hợp giúp giữ lưỡi dao cố định khi thay thế.',
      'Thân dao bền bỉ',
      'Dao được làm từ nhựa kỹ thuật chống mài mòn, giúp tăng độ bền khi sử dụng trong môi trường công nghiệp.',
      'Khóa an toàn',
      'Trang bị khóa an toàn giúp cố định lưỡi dao khi không sử dụng hoặc khi thay lưỡi.',
      'Thông số kỹ thuật',
      'Model: SECUPRO MERAK No.124001',
      'Trọng lượng: 59 g',
      'Độ sâu cắt: 9 mm',
      'Kích thước: 128 × 18 × 50 mm',
      'Chất liệu thân dao: Nhựa kỹ thuật chống mài mòn',
      'Cơ chế an toàn: Lưỡi tự động thu hồi',
      'Ứng dụng',
      'Cắt thùng carton',
      'Cắt bao bì đóng gói',
      'Cắt màng nhựa và màng film',
      'Cắt dây đai nhựa',
      'Sử dụng trong kho xưởng, logistics và nhà máy sản xuất',
      '----------------------',
      'The MARTOR SECUPRO MERAK No.124001 is a professional squeeze-grip safety knife designed for industrial cutting tasks. Manufactured by MARTOR (Germany), it offers reliable safety and ergonomic handling.',
      'This model is considered a compact version of the SECUPRO MARTEGO, providing excellent usability while maintaining high cutting performance.',
      'The knife features a fully automatic blade retraction mechanism, ensuring that the blade retracts immediately into the handle once the lever is released, significantly reducing the risk of workplace injuries.',
      'Its controlled cutting depth also helps protect goods inside cartons and packaging materials, making it ideal for warehousing, logistics, packaging lines, and industrial production environments.',
      'Key Features',
      'Ergonomic squeeze-grip trigger mechanism',
      'Fully automatic blade retraction for safety',
      'Tool-free blade replacement',
      'Integrated magnet to hold the blade securely',
      'Durable wear-resistant plastic body',
      'Applications',
      'Carton cutting',
      'Packaging materials',
      'Plastic films and wrapping',
      'Plastic strapping',
      'Warehouse and logistics operations',
      '#daoantoanmartor #daoantoan #daocatantoan #martorchinhhang #daocongnghiep #daorocthung #daorocmangphim #daocatdai #luoidaomartor',
    ],
    applications: [
      'Cắt thùng carton',
      'Cắt bao bì đóng gói',
      'Cắt màng nhựa và màng film',
      'Cắt dây đai nhựa',
      'Sử dụng trong kho xưởng, logistics và nhà máy sản xuất',
    ],
    images: [
      '/products/martor/secupro-merak-124001-1.webp',
      '/products/martor/secupro-merak-124001-2.webp',
      '/products/martor/secupro-merak-124001-3.webp',
    ],
    docPdf: '/catalogs/martor/secupro-merak-124001.pdf',
    kw: ['dao an toan', 'martor', 'secupro merak'],
  },

  // --- các hãng khác: dữ liệu demo, chờ thay bằng dữ liệu thật ---
  {
    part: 'MF-INOXCUT', name: 'Mũi mài INOX CUT', brand: 'morrisflex', category: 'mai-hoan-thien',
    series: 'INOX CUT', origin: 'Ireland', featured: true, tag: 'Bán chạy',
    desc: 'Mũi mài hợp kim cacbua vonfram chuyên mài inox, không sinh nhiệt cháy bề mặt.',
    specs: [['Vật liệu', 'Cacbua vonfram'], ['Đường kính', '6 mm'], ['Chuôi', '6 mm'], ['Tốc độ tối đa', '30.000 rpm']],
    kw: ['mui mai', 'ca rem', 'hop kim', 'inox'],
    pdf: { name: 'Morrisflex Carbide Burrs', size: '5.6 MB', pages: 24 },
  },
  {
    part: 'SPM80R', name: 'Mũi mài hợp kim SPM80R', brand: 'morrisflex', category: 'mai-hoan-thien',
    series: 'SPM', origin: 'Ireland',
    desc: 'Mũi mài đầu tròn, gợn xoắn kép cho tốc độ bóc tách vật liệu cao.',
    specs: [['Vật liệu', 'Cacbua vonfram'], ['Đường kính', '8 mm'], ['Kiểu răng', 'Xoắn kép'], ['Tốc độ tối đa', '28.000 rpm']],
    kw: ['mui mai', 'ca rem', 'spm'],
    pdf: { name: 'Morrisflex Carbide Burrs', size: '5.6 MB', pages: 24 },
  },
  {
    part: 'HEV-40250', name: 'Dao phay ngón HEV 4 me', brand: 'helical', category: 'cat-got-cnc',
    series: 'HEV', origin: 'Mỹ', featured: true,
    desc: 'Dao phay ngón 4 me phủ AlTiN, biên dạng biến bước giảm rung, phay thép tôi.',
    specs: [['Số me', '4'], ['Đường kính', '6.35 mm'], ['Phủ', 'AlTiN'], ['Vật liệu phôi', 'Thép tôi ≤ 55 HRC']],
    kw: ['dao phay ngon', 'end mill', 'helical'],
    pdf: { name: 'Helical End Mills', size: '8.1 MB', pages: 36 },
  },
  {
    part: 'HFV-30187', name: 'Dao phay ngón HFV 3 me', brand: 'helical', category: 'cat-got-cnc',
    series: 'HFV', origin: 'Mỹ',
    desc: 'Dao phay ngón 3 me cho nhôm, rãnh thoát phoi rộng, độ bóng bề mặt cao.',
    specs: [['Số me', '3'], ['Đường kính', '4.76 mm'], ['Vật liệu phôi', 'Nhôm, hợp kim màu']],
    kw: ['dao phay ngon', 'nhom', 'helical'],
    pdf: { name: 'Helical End Mills', size: '8.1 MB', pages: 36 },
  },
  {
    part: 'CH-C4', name: 'Dao CNC composite CH-C4', brand: 'corehog', category: 'composite',
    series: 'C-Series', origin: 'Mỹ',
    desc: 'Công cụ cắt CFRP / honeycomb, hình học chống tưa sợi, tuổi thọ cao.',
    specs: [['Ứng dụng', 'CFRP, composite'], ['Đường kính', '6 mm'], ['Phủ', 'Kim cương (CVD)']],
    kw: ['composite', 'cfrp', 'corehog'],
    pdf: { name: 'Corehog Composite Tools', size: '4.9 MB', pages: 20 },
  },
  {
    part: 'BT-R2', name: 'Máy vát mép Bevel BT-R2', brand: 'bevel-tools', category: 'vat-mep',
    series: 'R', origin: 'Hà Lan',
    desc: 'Dụng cụ vát mép và bo tròn cạnh kim loại cầm tay, thay dao nhanh.',
    specs: [['Góc vát', '45°'], ['Bo tròn', 'R2'], ['Vật liệu', 'Thép, nhôm']],
    kw: ['vat mep', 'bo tron', 'bevel'],
    pdf: { name: 'Bevel Tools Catalog', size: '2.7 MB', pages: 10 },
  },
  {
    part: 'AT-7033', name: 'Máy mài khí nén AT-7033', brand: 'ata', category: 'mai-hoan-thien',
    series: 'AT', origin: 'Ireland', featured: true, tag: 'Bán chạy',
    desc: 'Máy mài thẳng khí nén 1/4", vòng bi kín chịu bụi, cân bằng độ rung thấp.',
    specs: [['Tốc độ', '25.000 rpm'], ['Kẹp', '6 mm'], ['Áp suất', '6.3 bar'], ['Tiêu thụ khí', '0.6 m³/min']],
    kw: ['may mai', 'sung mai hoi', 'khi nen', 'ata'],
    pdf: { name: 'ATA Air Tools', size: '6.3 MB', pages: 28 },
  },
  {
    part: 'AT-5012', name: 'Máy chà nhám khí nén AT-5012', brand: 'ata', category: 'mai-hoan-thien',
    series: 'AT', origin: 'Ireland',
    desc: 'Máy chà nhám lệch tâm, đế 125 mm, hút bụi trung tâm, tay cầm chống rung.',
    specs: [['Đế', '125 mm'], ['Quỹ đạo', '5 mm'], ['Tốc độ', '10.000 opm']],
    kw: ['cha nham', 'khi nen', 'ata'],
    pdf: { name: 'ATA Air Tools', size: '6.3 MB', pages: 28 },
  },
  {
    part: 'FIAM-15C', name: 'Tua vít điện Fiam 15C', brand: 'fiam', category: 'siet-cong-nghiep',
    series: '15C', origin: 'Ý',
    desc: 'Tua vít điện công nghiệp điều khiển mô-men, ly hợp chính xác cho dây chuyền lắp ráp.',
    specs: [['Mô-men', '1.5 – 15 Nm'], ['Điều khiển', 'Ly hợp cơ khí'], ['Nguồn', 'BLDC']],
    kw: ['tua vit dien', 'fiam', 'lap rap'],
    pdf: { name: 'Fiam Screwdrivers', size: '3.4 MB', pages: 16 },
  },
  {
    part: '9502AX', name: 'Pa lăng cân bằng Tecna 9502AX', brand: 'tecna', category: 'nang-ha',
    series: 'Retractor', origin: 'Ý', featured: true,
    desc: 'Pa lăng cân bằng tải trọng, giữ dụng cụ lơ lửng, giảm mỏi cho công nhân lắp ráp.',
    specs: [['Tải trọng', '4 – 6 kg'], ['Hành trình cáp', '2.000 mm'], ['Kiểu', 'Zero Gravity']],
    kw: ['pa lang', 'ba lang', 'palang', 'can bang', 'tecna'],
    pdf: { name: 'Tecna Balancers', size: '4.0 MB', pages: 18 },
  },
  {
    part: 'LK-125', name: 'Bộ kẹp khuôn Lenzkes LK-125', brand: 'lenzkes', category: 'kep-khuon-phoi',
    series: 'Clamping', origin: 'Đức',
    desc: 'Bộ kẹp gá khuôn trên bàn máy công cụ, lực kẹp cao, tháo lắp nhanh không vặn ren dài.',
    specs: [['Rãnh T', '14 mm'], ['Lực kẹp', '25 kN'], ['Số chi tiết', '58']],
    kw: ['kep khuon', 'kep ga', 'lenzkes'],
    pdf: { name: 'Lenzkes Clamping', size: '5.2 MB', pages: 22 },
  },
  {
    part: 'RK-500', name: 'Máy phủ cứng Rocklinizer RK-500', brand: 'rocklinizer', category: 'phuc-hoi-be-mat',
    series: 'RK', origin: 'Mỹ',
    desc: 'Thiết bị phủ cứng bề mặt khuôn bằng phóng điện, tăng tuổi thọ cạnh sắc.',
    specs: [['Công suất', '500 VA'], ['Điện cực', 'Tungsten carbide'], ['Độ cứng phủ', '≤ 90 HRC']],
    kw: ['phu cung', 'khuon', 'rocklinizer'],
    pdf: { name: 'Rocklinizer Systems', size: '2.9 MB', pages: 12 },
  },
  {
    part: 'DF-BSG', name: 'Máy đánh bóng khuôn Diprofil BSG', brand: 'diprofil', category: 'mai-hoan-thien',
    series: 'BSG', origin: 'Thụy Điển',
    desc: 'Máy đánh bóng khuôn mẫu chuyển động thẳng, giũa và đá mài đổi nhanh.',
    specs: [['Hành trình', '3 mm'], ['Tần số', '6.500 spm'], ['Nguồn', 'Khí nén / điện']],
    kw: ['danh bong khuon', 'diprofil'],
    pdf: { name: 'Diprofil Polishing', size: '3.3 MB', pages: 14 },
  },
  {
    part: 'MP-350', name: 'Máy khắc dấu Technomark MP-350', brand: 'technomark', category: 'danh-dau',
    series: 'MarkPro', origin: 'Pháp', featured: true, tag: 'Mới',
    desc: 'Máy khắc dấu chấm peen khắc chữ, số, mã DataMatrix lên kim loại, truy xuất nguồn gốc.',
    specs: [['Vùng khắc', '120 × 100 mm'], ['Kiểu', 'Chấm peen (dot peen)'], ['Mã hỗ trợ', 'Text, DataMatrix']],
    kw: ['may khac dau', 'khac chu len sat', 'technomark'],
    pdf: { name: 'Technomark Marking', size: '4.6 MB', pages: 20 },
  },
  {
    part: 'TS-3D', name: 'Đầu dò 3D TSChorn TS-3D', brand: 'tschorn', category: 'do-can-chinh',
    series: '3D', origin: 'Đức',
    desc: 'Đầu dò 3D dò cạnh và tâm lỗ trên máy phay, đồng hồ so tích hợp độ chính xác cao.',
    specs: [['Độ chính xác', '0.01 mm'], ['Chuôi', '20 mm'], ['Đầu dò', 'Ø 4 mm']],
    kw: ['dau do', 'do kiem', 'tschorn'],
    pdf: { name: 'TSChorn Measuring', size: '2.4 MB', pages: 10 },
  },
  {
    part: 'SLOKY-TS15', name: 'Tua vít lực Sloky TS-15', brand: 'sloky', category: 'siet-luc-cam-tay',
    series: 'TS', origin: 'Đài Loan',
    desc: 'Tua vít lực chính xác cài đặt mô-men cố định, chống siết quá tay khi lắp mảnh dao.',
    specs: [['Dải mô-men', '0.6 – 1.5 Nm'], ['Sai số', '± 6%'], ['Đầu', 'Có thể thay']],
    kw: ['tua vit luc', 'to vit luc', 'sloky'],
    pdf: { name: 'Sloky Torque Drivers', size: '2.1 MB', pages: 9 },
  },
  {
    part: 'RTC-40', name: 'Khớp nối RTC-40', brand: 'rtc', category: 'khop-noi',
    series: 'RTC', origin: 'Đức',
    desc: 'Khớp nối truyền động bù lệch tâm, đàn hồi chống rung cho hệ trục.',
    specs: [['Đường kính trục', '40 mm'], ['Mô-men', '120 Nm'], ['Kiểu', 'Đàn hồi']],
    kw: ['khop noi', 'rtc', 'truyen dong'],
    pdf: { name: 'RTC Couplings', size: '1.9 MB', pages: 8 },
  },
  {
    part: 'BX-88', name: 'Hóa chất vệ sinh khuôn Buchem BX-88', brand: 'buchem', category: 've-sinh-khuon',
    series: 'BX', origin: 'Đức',
    desc: 'Dung dịch tẩy nhựa cháy và cặn khuôn ép, an toàn với bề mặt thép khuôn.',
    specs: [['Dạng', 'Bình xịt 500 ml'], ['Ứng dụng', 'Khuôn ép nhựa'], ['Điểm chớp cháy', '> 60 °C']],
    kw: ['hoa chat', 've sinh khuon', 'buchem'],
    pdf: { name: 'Buchem Mold Care', size: '2.2 MB', pages: 9 },
  },
  {
    part: 'HT-HSS8', name: 'Mũi khoan HSS-E Hartner 8mm', brand: 'hartner', category: 'cat-got-cnc',
    series: 'HSS-E', origin: 'Đức',
    desc: 'Mũi khoan thép gió coban HSS-E mài chính xác, khoan thép hợp kim và inox độ bền cao.',
    specs: [['Vật liệu', 'HSS-E (Co5)'], ['Đường kính', '8 mm'], ['Góc mũi', '135°'], ['Chuẩn', 'DIN 338']],
    kw: ['mui khoan', 'hss', 'hartner', 'cat got'],
    pdf: { name: 'Hartner Drilling', size: '3.5 MB', pages: 15 },
  },
  {
    part: 'KN-HSSDMOND', name: 'Lưỡi khoét hợp kim Karnasch', brand: 'karnasch', category: 'cat-got-cnc',
    series: 'Master Cut', origin: 'Đức',
    desc: 'Lưỡi khoét lõi (annular cutter) phủ TiAlN, khoan lỗ lớn nhanh trên thép tấm và dầm.',
    specs: [['Đường kính', '12 – 60 mm'], ['Chiều sâu cắt', '30 mm / 50 mm'], ['Phủ', 'TiAlN'], ['Chuôi', 'Weldon 19 mm']],
    kw: ['luoi khoet', 'annular', 'karnasch', 'khoan lo'],
    pdf: { name: 'Karnasch Master Cut', size: '6.8 MB', pages: 30 },
  },
]

export const NEWS: Article[] = [
  {
    slug: 'tungsten-carbide', cat: 'Kiến thức kỹ thuật', date: '28/07/2026',
    title: 'Tungsten Carbide: vì sao mũi mài hợp kim bền hơn thép gió',
    excerpt: 'Cấu trúc hạt cacbua vonfram và chất kết dính cobalt quyết định tuổi thọ và tốc độ bóc tách vật liệu.',
  },
  {
    slug: 'chon-dao-phay', cat: 'Giải pháp ứng dụng', date: '21/07/2026',
    title: 'Hướng dẫn chọn dao phay ngón theo vật liệu phôi',
    excerpt: 'Số me, lớp phủ và biên dạng — ba yếu tố cần cân nhắc khi phay nhôm, thép tôi hay composite.',
  },
  {
    slug: 'mta-2025', cat: 'Tin tức', date: '10/07/2026',
    title: 'Kim Thành Đông tại triển lãm MTA Vietnam 2025',
    excerpt: 'KTĐ giới thiệu danh mục dụng cụ an toàn Martor và pa lăng cân bằng Tecna tới khách hàng công nghiệp.',
  },
]

export const NEWS_CATEGORIES = ['Kiến thức kỹ thuật', 'Giải pháp ứng dụng', 'Tin tức'] as const

// ---------------------------------------------------------------- lookups

const brandBySlug = new Map(BRANDS.map((b) => [b.slug, b]))
const categoryBySlug = new Map(CATEGORIES.map((c) => [c.slug, c]))

export function getBrand(slug: string): Brand | undefined {
  return brandBySlug.get(slug)
}

export function brandName(slug: string): string {
  return brandBySlug.get(slug)?.name ?? slug
}

export function getCategory(slug: string): Category | undefined {
  return categoryBySlug.get(slug)
}

export function categoryName(slug: string): string {
  return categoryBySlug.get(slug)?.name ?? slug
}

export function countByBrand(slug: string): number {
  return PRODUCTS.filter((p) => p.brand === slug).length
}

export function countByCategory(slug: string): number {
  return PRODUCTS.filter((p) => p.category === slug).length
}

/** Spec C0: slug = {ten-khong-dau}-{part-number}, lowercase, hyphenated. */
export function productSlug(p: Product): string {
  return slugify(`${p.name} ${p.part}`)
}

const productsBySlug = new Map(PRODUCTS.map((p) => [productSlug(p), p]))

export function getProductBySlug(slug: string): Product | undefined {
  return productsBySlug.get(slug)
}

export function getProductByPart(part: string): Product | undefined {
  return PRODUCTS.find((p) => p.part === part)
}

export function productSectors(p: Product): string[] {
  return CATEGORY_SECTORS[p.category] ?? []
}

export function pdfLine(p: Product): string | null {
  return p.pdf ? `${p.pdf.name} · ${p.pdf.size} · ${p.pdf.pages} tr.` : null
}

/** The five prescribed photo angles for a representative part (spec C3). */
export const GALLERY_VIEWS = ['Mặt trước', 'Mặt bên', 'Góc 45°', 'Chi tiết cơ cấu', 'Đang sử dụng'] as const
